/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative */

#ifndef _Included_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
#define _Included_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __create_share__
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[BII)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1create_1share_1_1
  (JNIEnv *, jclass, jobjectArray, jbyteArray, jint, jint);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __generate_privpub_key__
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;IIIZ)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1generate_1privpub_1key_1_1
  (JNIEnv *, jclass, jobjectArray, jint, jint, jint, jboolean);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __enc__
 * Signature: (Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;JILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1enc_1_1
  (JNIEnv *, jclass, jobject, jlong, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __enc_list__
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[JILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1enc_1list_1_1
  (JNIEnv *, jclass, jobjectArray, jlongArray, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __partial_dec__
 * Signature: (Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;IIIJ[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1partial_1dec_1_1
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jlong, jobjectArray);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __partial_dec_lst__
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;IIIJ[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1partial_1dec_1lst_1_1
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint, jint, jint, jlong, jobjectArray);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __final_dec__
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;IIJJ[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)J
 */
JNIEXPORT jlong JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1final_1dec_1_1
  (JNIEnv *, jclass, jobjectArray, jobject, jint, jint, jlong, jlong, jobjectArray);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __add__
 * Signature: (Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;ILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1add_1_1
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __add_vec__
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;ILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1add_1vec_1_1
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __sum_vec__
 * Signature: (Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;ILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1sum_1vec_1_1
  (JNIEnv *, jclass, jobject, jobjectArray, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __mul__
 * Signature: (Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;JILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1mul_1_1
  (JNIEnv *, jclass, jobject, jobject, jlong, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __mul_elementWise__
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[JILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1mul_1elementWise_1_1
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jlongArray, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __div__
 * Signature: (Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;JILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1div_1_1
  (JNIEnv *, jclass, jobject, jobject, jlong, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    __div_elementWise__
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[JILcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative__1_1div_1elementWise_1_1
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jlongArray, jint, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    test_generate_priv_key
 * Signature: (Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;IIII)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative_test_1generate_1priv_1key
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    test_IO
 * Signature: (Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative_test_1IO__Lcom_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative_signedByteArray_2Lcom_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative_signedByteArray_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative
 * Method:    test_IO
 * Signature: ([Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;[Lcom/jdt/fedlearn/core/encryption/distributedPaillier/DistributedPaillierNative/signedByteArray;)V
 */
JNIEXPORT void JNICALL Java_com_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative_test_1IO___3Lcom_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative_signedByteArray_2_3Lcom_jdt_fedlearn_core_encryption_distributedPaillier_DistributedPaillierNative_signedByteArray_2
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
