/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DistributedPaillier_signedByteArray */

#ifndef _Included_DistributedPaillier_signedByteArray
#define _Included_DistributedPaillier_signedByteArray
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
