/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DistributedPaillier_dist_paillier_privkey */

#ifndef _Included_DistributedPaillier_dist_paillier_privkey
#define _Included_DistributedPaillier_dist_paillier_privkey
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
