/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DistributedPaillier_dist_paillier_pubkey */

#ifndef _Included_DistributedPaillier_dist_paillier_pubkey
#define _Included_DistributedPaillier_dist_paillier_pubkey
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
